# Generated by Django 2.2 on 2019-05-30 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SegmentTrackerAPP', '0004_auto_20190420_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
